name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        run: npm install --no-package-lock

      - name: Build
        run: npm run build

      - name: Override gitignore
        run: |
          echo "node_modules" > .gitignore
          echo ".npm" >> .gitignore

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build: ${{ github.sha }}"
          branch: build
          commit_options: "--no-verify"
