name: Publish
on: workflow_dispatch

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x 
          cache: "npm"

      - run: npm install --no-package-lock
      - name: "Create Release Pull Request or Publish"
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          publish: npm run release

permissions: 
  pull-requests: write
  contents: write
  actions: write
  checks: write
  
          
  